services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../app/static:/app/static
      - ./nginx/ssl:/etc/nginx/ssl 
    depends_on:
      - fastapi