name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Create .env.minio
        run: |
          echo "MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}" >> ./env/.env.minio
          echo "MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}" >> ./env/.env.minio
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ./env/.env.minio
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ./env/.env.minio

      - name: Build images
        run: docker compose -f ./docker/docker-compose.minio.yaml -f ./docker/docker-compose.web.yml --env-file ./env/.env.minio up --build -d

      - name: Check running containers
        run: docker ps -a
      
      - name: Wait for services to be ready
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:9000/minio/health/live && curl -f http://localhost:8000; then
              break
            else
              echo "Waiting for services..."
              sleep 5
            fi
          done

      - name: Stop and remove containers
        run: docker compose -f ./docker/docker-compose.minio.yaml -f ./docker/docker-compose.web.yml --env-file ./env/.env.minio  down
